### ISSUE TITLE
Rewards Plot

### ISSUE THREAD

**Issue by jp3477** [cxrodgers/mouse-cloud#4]
Setup: A series of line graphs that show the water output per day for all boxes. The x-axis contains the last 10 or so days of the box's activity. The y-axis contains volume of water (not sure if range should be dynamic or preset) . There are two different curves on each graph. One represents the volume output by the right pipe, and the other represents the volume output by the left pipe. They should be in different colors, and be identified by a legend. If the volume of water is over 180, change graph title red to indicate there is a problem.

**Comment by cxrodgers** [comment]
Looks good!

Probably by "volume over 180" you mean "reward duration over 180", which typically indicates that the reward valve is getting clogged. 

As for y-axis, I would say it should default to a reasonable range (3-7 uL), but then autoscale if the values are outside of this range.
